services:
  - type: web
    name: nhutinportal
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        value: dpg-d6kru3ua2pns7396assg-a.singapore-postgres.render.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: nhutin_portal
      - key: DB_USER
        value: nhutin_user
      - key: DB_PASSWORD
        value: q4t1KUVWizmK3jjHCTy7xlkIRMjyDOJ8
      - key: DB_SSLMODE
        value: require
